services:
  apache:
    container_name: apacheserver
    image: httpd
    links:
      - node
    ports:
      - "80:8080"
    volumes:
      - /var/www/html:/html

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./nodejs:/home/node/app
    links:
      - db
    expose:
      - "8081"
    command: "npm start"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'banco'
      MYSQL_USER: 'nodejs'
      MYSQL_PASSWORD: 'node3j5'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql:/var/lib/mysql
