apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8000
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
