version : '3'

services:
  interfaz:
    container_name: frontend-proyecto
    working_dir: /usr/src/app
    image: node:8
    links:
      - backend
    ports:
      - "8085:8080"
    volumes:
      -  ./frontend:/usr/src/app
    command: bash -c "npm install && npm run serve"

  backend:
    container_name: backend-proyecto
    image: node:8
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
      DB_NAME: 'banco'
      DB_USER: 'nodejs'
      DB_PASSWORD: 'node3j5'
      DB_ROOT_PASSWORD: 'root'
    volumes:
      - ./backend:/usr/src/app
    links:
      - database
    ports:
      - "8081:8000"
    command: bash -c "npm install && node app.js"

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'banco'
      MYSQL_USER: 'nodejs'
      MYSQL_PASSWORD: 'node3j5'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql:/var/lib/mysql
