apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: interfaz
  name: interfaz
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: interfaz
    spec:
      containers:
      - args:
        - bash
        - -c
        - npm install && npm run serve
        image: node:8
        name: frontend-proyecto
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: interfaz-claim0
        workingDir: /usr/src/app
      restartPolicy: Always
      volumes:
      - name: interfaz-claim0
        persistentVolumeClaim:
          claimName: interfaz-claim0
status: {}
